apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: antbic6g5-dotnet-basic
  janus-idp.io/tekton: antbic6g5-dotnet-basic
  backstage.io/kubernetes-id: antbic6g5-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: antbic6g5-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
